# Generated by Django 5.0.7 on 2024-07-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('any_suggestions', models.CharField(max_length=100)),
                ('improve', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='new_prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=1000)),
                ('label_l', models.CharField(max_length=100)),
                ('label_2', models.CharField(max_length=100)),
                ('label_3', models.CharField(max_length=100)),
                ('label_n', models.CharField(max_length=100)),
                ('output', models.CharField(max_length=1000)),
            ],
        ),
    ]
