# Generated by Django 5.0.7 on 2024-07-23 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiProvider',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('any_suggestions', models.CharField(max_length=100)),
                ('improve', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='new_prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=1000)),
                ('output', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ChatModels',
            fields=[
                ('chat_model_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_model_name', models.CharField(max_length=60)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestapp.apiprovider')),
            ],
        ),
    ]
