# Generated by Django 5.0.7 on 2024-07-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_prompt',
            name='prompt_name',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
